exclude:
  - 'grunt'
  - 'less'
  - 'node_modules'
  - 'src'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Gruntfile.js'
  - 'package.json'
  - 'README.md'
  - 'CNAME'
  - 'HTML1.html'
  - 'HTML2.html'
  - 'HTML3.html'
  - 'HTML4.html'
  - 'HTML5.html'
  - 'HTML6.html'
  - 'HTML7.html'
  - 'HTML8.html'
  - 'HTML9.html'
  - 'HTML10.html'
  - 'HTML11.html'
  - 'HTML12.html'
